name: Build and Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: zip -qq -r TwitchShark.rmod . -x '*.csproj' -x '*.rmod' 
        working-directory: TwitchShark
      
      - run: npm i --location=global semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec
      
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - uses: actions/upload-artifact@v2
        with:
          name: TwitchSharkMod
          path: TwitchShark.rmod
